[package]
name = "bitrust-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
prost = "0.14.3"
tonic = { version = "0.14.2", default-features = false, features = ["codegen"] }
tonic-prost = "0.14.2"

[build-dependencies]
tonic-prost-build = "0.14.2"

[lints]
workspace = true
