[package]
name = "bitrust-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitrust-proto = { path = "../bitrust-proto"}
tokio = { version = "1.49.0", features = ["full"] }
tonic = "0.14.2"

[lints]
workspace = true
